language: go
sudo: false
dist: xenial
git:
  depth: false
go:
  - tip
os:
  - linux

install:
  - npm install -g postcss-cli
  - npm install -g autoprefixer
  - go get --tags extended  github.com/gohugoio/hugo
script:
  - ./deploy.sh
