# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        #personal_token: ${{ secrets.PERSONAL_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src_path: /.
        dst_path: /.
        dst_repo_name: ros-agriculture.github.io
        dst_branch: master
        src_branch: gh-pages
        src_wiki: false
        dst_wiki: false
